apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

namespace: webserver

images:
  - name: nginx
    newName: joelfernandes01/nginx
    newTag: v1.0.0
